### ISSUE TITLE
[功能请求] Linux和Mac的安装包

### ISSUE THREAD

**Issue by lanyeeee** [lanyeeee/bilibili-manga-watermark-remover#15]
### 原因

需要在Linux或Mac上使用这个工具

### 功能简述

Release页面添加Linux和Mac的安装包

### 功能逻辑

Release页面添加Linux和Mac的安装包

### 实现参考

https://github.com/tauri-apps/tauri-action

**Comment by lanyeeee** [comment]
真的有人需要这个么🤔

**Comment by redwhale-q** [comment]
我献上无限赞美！！这个程序拯救了一个收藏强迫癖！

**Comment by lanyeeee** [comment]
别急，记得保留原档，预计下个月我会发优化后的算法。
现在你调色还是能看到水印处有瑕疵的(虽然肉眼看不出)，优化后的算法即使调色水印也只剩几个零星的像素点了(甚至完全去除)

**Comment by lanyeeee** [comment]
已在 [v0.7.0](https://github.com/lanyeeee/bilibili-manga-watermark-remover/releases/tag/v0.7.0) 实现
