### ISSUE TITLE
[Bug] 同分辨率，不同水印的漫画会被跳过

### ISSUE THREAD

**Issue by lanyeeee** [lanyeeee/bilibili-manga-watermark-remover#4]
### 问题描述

例如之前自动生成了2000x2030的背景水印图  
以后再碰到相同尺寸但是水印不同的漫画，就不会自动生成，而是跳过  
这是一个潜在的问题，暂时没有实际遇到

### 预期行为

再碰到相同分辨率的漫画不会跳过

### 实际行为

再碰到相同分辨率的漫画会跳过

### 工具版本号

v0.1

**Comment by EveZero0** [comment]
化物语 会遇到这种情况

**Comment by lanyeeee** [comment]
> 化物语 会遇到这种情况

@EveZero0 方便把 化物语 传个度盘吗

**Comment by EveZero0** [comment]
https://www.mediafire.com/folder/vx9sy3limov59/Bakemonogatari

**Comment by lanyeeee** [comment]
化物语 的问题请移步 #8
