### ISSUE TITLE
[Bug] 总是显示”缺少黑色背景水印图“

### ISSUE THREAD

**Issue by zhiqumujin** [lanyeeee/bilibili-manga-watermark-remover#44]
### 问题描述

![image](https://github.com/user-attachments/assets/7e520bc7-84ff-4b28-accd-179245a5a0fe)
![image](https://github.com/user-attachments/assets/7bba9d99-4e16-4e71-96f9-68a391da9c7f)
总是显示”缺少黑色背景水印图“，手动截取也没用

### 预期行为

能成功生成背景水印图，能正常生成去除水印的漫画图片

### 实际行为

无法生成黑色背景水印图

### 工具版本号

0.5

**Comment by zhiqumujin** [comment]
![image](https://github.com/user-attachments/assets/fcf43c08-2469-4202-a093-76ed77246030)
《葬送的芙莉莲》的黑色和白色背景水印图也无法生成

**Comment by lanyeeee** [comment]
看看这个 #1

另外我注意到，你漫画目录下的图片很少，只有十几张，找不到条件合适的图片是正常的
还有什么疑问欢迎补充

**Comment by zhiqumujin** [comment]
我遇到了和这个相同的问题https://github.com/lanyeeee/bilibili-manga-downloader/issues/6，显示?token=
0: 下载图片 ?token= 失败
1: builder error
2: relative URL without a base
我第一次按照第一个办法，删除了buvid3引号里的东西，确实有用，于是我才能提出上述问题。但是刚才我想多下几话时，又出现了下载图片失败的错误，并且上述方法失灵，依旧下载失败
![image](https://github.com/user-attachments/assets/948ad7d1-63f2-4c7a-987c-4b2675402103)
![image](https://github.com/user-attachments/assets/4cfde4b6-b69f-4f4f-b468-2b1db465e160)
![image](https://github.com/user-attachments/assets/e32ce3eb-61b0-4ac3-8047-ee3f73ab47e7)

**Comment by lanyeeee** [comment]
下载问题已在 [哔哩哔哩漫画下载器](https://github.com/lanyeeee/bilibili-manga-downloader) v0.4 修复
关于去水印还有什么问题吗？

**Comment by zhiqumujin** [comment]
![image](https://github.com/user-attachments/assets/42b86c28-3e3e-4216-ae3c-b5f3024c1d58)
![image](https://github.com/user-attachments/assets/ecaea84c-a2a1-4f13-b6ad-f325a220cf04)
标题一样的话会下载失败

**Comment by lanyeeee** [comment]
这个问题你去[隔壁](https://github.com/lanyeeee/bilibili-manga-downloader/issues)开一个issue吧，我有空再修，优先级不是很高
关于下载器的问题尽量不要在这里讨论了
如果去水印没什么疑问了就把这个issue关了吧
