### ISSUE TITLE
[Bug] 部分话数去水印失败

### ISSUE THREAD

**Issue by zhiqumujin** [lanyeeee/bilibili-manga-watermark-remover#45]
### 问题描述

部分话数明明白色和黑色背景水印图都有，但依旧有水印

### 预期行为

成功生成白色和黑色背景水印图的尺寸的漫画图片均无水印

### 实际行为

![image](https://github.com/user-attachments/assets/1e786367-48fd-4dbc-915a-9461d5a7b4af)
![image](https://github.com/user-attachments/assets/e382320d-1b1b-49a3-beca-771ded27e409)
![image](https://github.com/user-attachments/assets/62a6d550-d794-4639-8854-5c2e2cd864f3)
有些2000x3000和2000x2844尺寸的话数去水印失败

### 工具版本号

0.6

**Comment by zhiqumujin** [comment]
值得一提的是，这些问题都出现在45话之前的话数

**Comment by lanyeeee** [comment]
看看这个 #8
