### ISSUE TITLE
[功能请求] 支持输出png格式

### ISSUE THREAD

**Issue by lanyeeee** [lanyeeee/bilibili-manga-watermark-remover#6]
### 原因

jpeg是有损压缩算法

### 功能简述

输出png格式的图片

### 功能逻辑

给出一个单选按钮，用户自行选择输出格式

**Comment by lanyeeee** [comment]
真的有人需要这个功能么🤔

**Comment by sbsdlat** [comment]
现在是JPG转JPG，相当于折损两次。加个导出为PNG功能是挺好的，对黑白图片，使用PNG8格式保存；彩图用PNG24格式保存。
